module.exports = {
    AddGuild: require("./Guild/AddGuild2DB"),
    PremCheck: require("./Guild/PremChecker.js"),
    PartnerCheck: require("./Guild/PartnerChecker.js"),
    ModMailCheck: require("./Guild/ModMailChecker.js"),
    VeriChannelCheck: require("./Guild/VerChannelCheck.js"),
    VeriRoleCheck: require("./Guild/VeriChannelRole.js"),
    UnveriRoleCheck: require("./Guild/UnveriRoleCheck.js"),
    WelcomeChannelCheck: require("./Guild/WelcomeChannelCheck.js"),
    EventsChannelCheck: require("./Guild/EventsChannelCheck.js"),
    GuildModsCheck: require("./Guild/ModsCheck.js"),
    StaffCheck: require("./Guild/StaffCheck.js"),
    BannedWordsCheck: require("./Guild/BannedWordsCheck.js"),
    WhiteListedLinksCheck: require("./Guild/WhiteListedLinks.js"),
    DellAllLinksCheck: require("./Guild/DellAllLinksCheck.js"),
    LogChannelCheck: require("./Guild/LogChannel.js"),
    LevelRolesCheck: require("./Guild/LevelRoles.js"),
    LevelXPsCheck: require("./Guild/LevelXPsCheck.js"),
    CoinNameCheck: require("./Guild/CoinName.js")
}